/*
 * Copyright 2008-2010 The sinkCell Development Team
 *
 * This file is part of sinkCell.
 *
 * sinkCell is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software
 * Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *
 * sinkCell is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
 * A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * sinkCell; if not, write to the Free Software Foundation, Inc., 51 Franklin St,
 * Fifth Floor, Boston, MA 02110-1301 USA
 */

/*
 * Configuration.java
 *
 * Created on 02-oct-2010, 12:55:39
 */
package sinkjava;

/**
 *
 * @author sandra
 */
public class Configuration extends javax.swing.JDialog {

    Parameters parameters;
    int status = 0;

    /** Creates new form configuration */
    public Configuration(Parameters parameters) {
        this.parameters = parameters;

        initComponents();

        if (parameters != null) {
            this.setParameters(parameters);
        } else {
            System.out.println("It is not possible to read the config file");
        }
    }

    public void setParameters(Parameters parameters) {
        ciclesSlider.setValue(parameters.cicles);
        ciclesTF.setText(String.valueOf(parameters.cicles));

        populationSlider.setValue(parameters.population);
        populationTF.setText(String.valueOf(parameters.population));

        mortalitySlider.setValue(parameters.mortality);
        mortalityTF.setText(String.valueOf(parameters.mortality));

        patchSlider.setValue(parameters.patch);
        patchTF.setText(String.valueOf(parameters.patch));

        sizeSlider.setValue(parameters.size);
        sizeTF.setText(String.valueOf(parameters.size));

        var1.setValue(parameters.var1);
        var2.setValue(parameters.var2);
        var3.setValue(parameters.var3);
        var4.setValue(parameters.var4);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ciclesSlider = new javax.swing.JSlider();
        ciclesTF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        populationSlider = new javax.swing.JSlider();
        populationTF = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        mortalitySlider = new javax.swing.JSlider();
        mortalityTF = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        patchSlider = new javax.swing.JSlider();
        patchTF = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        sizeSlider = new javax.swing.JSlider();
        sizeTF = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        var1 = new javax.swing.JSlider();
        jLabel7 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        var2 = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        var3 = new javax.swing.JSlider();
        jLabel11 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        var4 = new javax.swing.JSlider();
        jLabel13 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(452, 450));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(450, 450));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setOpaque(false);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addComponent(okButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel1.setLayout(new java.awt.GridLayout(5, 1));

        jPanel6.setMinimumSize(new java.awt.Dimension(400, 63));
        jPanel6.setPreferredSize(new java.awt.Dimension(400, 67));
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cicles");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel3.setMaximumSize(new java.awt.Dimension(67, 15));
        jLabel3.setMinimumSize(new java.awt.Dimension(67, 15));
        jLabel3.setPreferredSize(new java.awt.Dimension(67, 15));
        jPanel6.add(jLabel3, new java.awt.GridBagConstraints());

        ciclesSlider.setMajorTickSpacing(100000);
        ciclesSlider.setMaximum(100000);
        ciclesSlider.setMinorTickSpacing(10000);
        ciclesSlider.setPaintTicks(true);
        ciclesSlider.setMinimumSize(new java.awt.Dimension(250, 63));
        ciclesSlider.setPreferredSize(new java.awt.Dimension(250, 67));
        ciclesSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ciclesSliderStateChanged(evt);
            }
        });
        jPanel6.add(ciclesSlider, new java.awt.GridBagConstraints());

        ciclesTF.setMinimumSize(new java.awt.Dimension(60, 25));
        ciclesTF.setPreferredSize(new java.awt.Dimension(60, 25));
        ciclesTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciclesTFActionPerformed(evt);
            }
        });
        jPanel6.add(ciclesTF, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel6);

        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Population");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel4.add(jLabel1, new java.awt.GridBagConstraints());

        populationSlider.setMajorTickSpacing(10000);
        populationSlider.setMaximum(10000);
        populationSlider.setMinorTickSpacing(1000);
        populationSlider.setPaintTicks(true);
        populationSlider.setMinimumSize(new java.awt.Dimension(250, 48));
        populationSlider.setPreferredSize(new java.awt.Dimension(250, 52));
        populationSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                populationSliderStateChanged(evt);
            }
        });
        jPanel4.add(populationSlider, new java.awt.GridBagConstraints());

        populationTF.setMinimumSize(new java.awt.Dimension(60, 25));
        populationTF.setPreferredSize(new java.awt.Dimension(60, 25));
        populationTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                populationTFActionPerformed(evt);
            }
        });
        jPanel4.add(populationTF, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mortality");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel2.setMaximumSize(new java.awt.Dimension(67, 15));
        jLabel2.setMinimumSize(new java.awt.Dimension(67, 15));
        jLabel2.setPreferredSize(new java.awt.Dimension(67, 15));
        jPanel5.add(jLabel2, new java.awt.GridBagConstraints());

        mortalitySlider.setMajorTickSpacing(10000);
        mortalitySlider.setMaximum(10000);
        mortalitySlider.setMinorTickSpacing(1000);
        mortalitySlider.setPaintTicks(true);
        mortalitySlider.setMinimumSize(new java.awt.Dimension(250, 48));
        mortalitySlider.setPreferredSize(new java.awt.Dimension(250, 52));
        mortalitySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mortalitySliderStateChanged(evt);
            }
        });
        jPanel5.add(mortalitySlider, new java.awt.GridBagConstraints());

        mortalityTF.setMinimumSize(new java.awt.Dimension(60, 25));
        mortalityTF.setPreferredSize(new java.awt.Dimension(60, 25));
        mortalityTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mortalityTFActionPerformed(evt);
            }
        });
        jPanel5.add(mortalityTF, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel5);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Patch");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel4.setPreferredSize(new java.awt.Dimension(67, 15));
        jPanel7.add(jLabel4, new java.awt.GridBagConstraints());

        patchSlider.setMajorTickSpacing(1000);
        patchSlider.setMaximum(1000);
        patchSlider.setMinorTickSpacing(100);
        patchSlider.setPaintTicks(true);
        patchSlider.setMinimumSize(new java.awt.Dimension(250, 48));
        patchSlider.setPreferredSize(new java.awt.Dimension(250, 52));
        patchSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                patchSliderStateChanged(evt);
            }
        });
        jPanel7.add(patchSlider, new java.awt.GridBagConstraints());

        patchTF.setMinimumSize(new java.awt.Dimension(60, 25));
        patchTF.setPreferredSize(new java.awt.Dimension(60, 25));
        patchTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patchTFActionPerformed(evt);
            }
        });
        jPanel7.add(patchTF, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel7);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Size");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel5.setPreferredSize(new java.awt.Dimension(67, 15));
        jPanel8.add(jLabel5, new java.awt.GridBagConstraints());

        sizeSlider.setMajorTickSpacing(1000);
        sizeSlider.setMaximum(1000);
        sizeSlider.setMinorTickSpacing(100);
        sizeSlider.setPaintTicks(true);
        sizeSlider.setMinimumSize(new java.awt.Dimension(250, 48));
        sizeSlider.setPreferredSize(new java.awt.Dimension(250, 52));
        sizeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sizeSliderStateChanged(evt);
            }
        });
        jPanel8.add(sizeSlider, new java.awt.GridBagConstraints());

        sizeTF.setMinimumSize(new java.awt.Dimension(60, 25));
        sizeTF.setPreferredSize(new java.awt.Dimension(60, 25));
        sizeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeTFActionPerformed(evt);
            }
        });
        jPanel8.add(sizeTF, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel8);

        jTabbedPane1.addTab("General Configuration", jPanel1);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Cells changes to 0 if:"));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel6.setText("Neiborhood is >=");
        jPanel10.add(jLabel6);

        var1.setMajorTickSpacing(8);
        var1.setMaximum(8);
        var1.setMinorTickSpacing(1);
        var1.setPaintTicks(true);
        var1.setSnapToTicks(true);
        var1.setPreferredSize(new java.awt.Dimension(100, 44));
        jPanel10.add(var1);

        jLabel7.setText("and habitat= 1");
        jPanel10.add(jLabel7);

        jPanel9.add(jPanel10);

        jLabel8.setText("Neiborhood is >=");
        jPanel11.add(jLabel8);

        var2.setMajorTickSpacing(8);
        var2.setMaximum(8);
        var2.setMinorTickSpacing(1);
        var2.setPaintTicks(true);
        var2.setSnapToTicks(true);
        var2.setPreferredSize(new java.awt.Dimension(100, 44));
        jPanel11.add(var2);

        jLabel9.setText("and habitat= 0");
        jPanel11.add(jLabel9);

        jPanel9.add(jPanel11);

        jPanel3.add(jPanel9);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Cells changes to 1 if:"));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel10.setText("Neiborhood is >=");
        jPanel13.add(jLabel10);

        var3.setMajorTickSpacing(8);
        var3.setMaximum(8);
        var3.setMinorTickSpacing(1);
        var3.setPaintTicks(true);
        var3.setSnapToTicks(true);
        var3.setPreferredSize(new java.awt.Dimension(100, 44));
        jPanel13.add(var3);

        jLabel11.setText("and habitat= 1");
        jPanel13.add(jLabel11);

        jPanel12.add(jPanel13);

        jLabel12.setText("Neiborhood is >=");
        jPanel14.add(jLabel12);

        var4.setMajorTickSpacing(8);
        var4.setMaximum(8);
        var4.setMinorTickSpacing(1);
        var4.setPaintTicks(true);
        var4.setSnapToTicks(true);
        var4.setPreferredSize(new java.awt.Dimension(100, 44));
        jPanel14.add(var4);

        jLabel13.setText("and habitat= 0");
        jPanel14.add(jLabel13);

        jPanel12.add(jPanel14);

        jPanel3.add(jPanel12);
        jPanel12.getAccessibleContext().setAccessibleName("Cells changes to 1 if:");

        jTabbedPane1.addTab("Internal Variables", jPanel3);

        add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    public int getStatus() {
        return status;
    }

    public Parameters getParameters() {
        return this.parameters;
    }

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        parameters.cicles = this.ciclesSlider.getValue();
        parameters.mortality = this.mortalitySlider.getValue();
        parameters.patch = this.patchSlider.getValue();
        parameters.population = this.populationSlider.getValue();
        parameters.size = this.sizeSlider.getValue();
        parameters.var1 = this.var1.getValue();
        parameters.var2 = this.var2.getValue();
        parameters.var3 = this.var3.getValue();
        parameters.var4 = this.var4.getValue();

        status = 1;

        setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed

    private void sizeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeTFActionPerformed
        String value = sizeTF.getText();
        try {
            int intValue = Integer.parseInt(value);
            sizeSlider.setValue(intValue);
        } catch (Exception e) {
            System.out.println("The number format is not correct");
        }
}//GEN-LAST:event_sizeTFActionPerformed

    private void sizeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sizeSliderStateChanged
        int value = sizeSlider.getValue();
        sizeTF.setText(String.valueOf(value));

}//GEN-LAST:event_sizeSliderStateChanged

    private void patchTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patchTFActionPerformed
        String value = patchTF.getText();
        try {
            int intValue = Integer.parseInt(value);
            patchSlider.setValue(intValue);
        } catch (Exception e) {
            System.out.println("The number format is not correct");
        }
}//GEN-LAST:event_patchTFActionPerformed

    private void patchSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_patchSliderStateChanged
        int value = patchSlider.getValue();
        patchTF.setText(String.valueOf(value));
}//GEN-LAST:event_patchSliderStateChanged

    private void mortalityTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mortalityTFActionPerformed
        String value = mortalityTF.getText();
        try {
            int intValue = Integer.parseInt(value);
            mortalitySlider.setValue(intValue);
        } catch (Exception e) {
            System.out.println("The number format is not correct");
        }
}//GEN-LAST:event_mortalityTFActionPerformed

    private void mortalitySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mortalitySliderStateChanged
        int value = mortalitySlider.getValue();
        mortalityTF.setText(String.valueOf(value));
}//GEN-LAST:event_mortalitySliderStateChanged

    private void populationTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_populationTFActionPerformed
        String value = populationTF.getText();
        try {
            int intValue = Integer.parseInt(value);
            populationSlider.setValue(intValue);
        } catch (Exception e) {
            System.out.println("The number format is not correct");
        }
}//GEN-LAST:event_populationTFActionPerformed

    private void populationSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_populationSliderStateChanged
        int value = populationSlider.getValue();
        populationTF.setText(String.valueOf(value));
}//GEN-LAST:event_populationSliderStateChanged

    private void ciclesTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciclesTFActionPerformed
        String value = ciclesTF.getText();
        try {
            int intValue = Integer.parseInt(value);
            ciclesSlider.setValue(intValue);
        } catch (Exception e) {
            System.out.println("The number format is not correct");
        }
}//GEN-LAST:event_ciclesTFActionPerformed

    private void ciclesSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ciclesSliderStateChanged
        int value = ciclesSlider.getValue();
        ciclesTF.setText(String.valueOf(value));
}//GEN-LAST:event_ciclesSliderStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JSlider ciclesSlider;
    private javax.swing.JTextField ciclesTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSlider mortalitySlider;
    private javax.swing.JTextField mortalityTF;
    private javax.swing.JButton okButton;
    private javax.swing.JSlider patchSlider;
    private javax.swing.JTextField patchTF;
    private javax.swing.JSlider populationSlider;
    private javax.swing.JTextField populationTF;
    private javax.swing.JSlider sizeSlider;
    private javax.swing.JTextField sizeTF;
    private javax.swing.JSlider var1;
    private javax.swing.JSlider var2;
    private javax.swing.JSlider var3;
    private javax.swing.JSlider var4;
    // End of variables declaration//GEN-END:variables

    private void setOpaque(boolean b) {
    }
}
